---
- name: prepare
  hosts: all
  gather_facts: false
  become: true
  vars:
    run_in_container: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install common utils
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - net-tools
        - htop